package main

import "net/http"

func (app *app) routes() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /api/health/ready", app.readiness)
	mux.HandleFunc("GET /api/preview", app.getPreviewInfo)
	if app.environmentService != nil {
		mux.HandleFunc("GET /api/project/{projectId}/settings/environments", app.getEnvironmentSettings)
		mux.HandleFunc("PUT /api/project/{projectId}/settings/environments", app.putEnvironmentSettings)
		mux.HandleFunc("GET /api/environments/project/{projectId}/check", app.checkEnvironmentConnection)
		mux.HandleFunc("GET /api/environments/project/{projectId}/branches", app.getEnvironmentBranches)
		mux.HandleFunc("GET /api/environments/project/{projectId}", app.listEnvironments)
		mux.HandleFunc("POST /api/environments/project/{projectId}", app.createEnvironment)
		mux.HandleFunc("POST /api/environments/project/{projectId}/bulk", app.bulkEnvironmentAction)
		mux.HandleFunc("GET /api/environments/task/{taskId}", app.listEnvironments)
		mux.HandleFunc("POST /api/environments/task/{taskId}", app.createEnvironment)
		mux.HandleFunc("GET /api/environment/{id}", app.getEnvironment)
		mux.HandleFunc("PUT /api/environment/{id}", app.editEnvironment)
		mux.HandleFunc("GET /api/environment/{id}/logs", app.environmentLogs)
		mux.HandleFunc("GET /api/environment/{id}/source", app.environmentSourceStatus)
		mux.HandleFunc("POST /api/environment/{id}/{action}", app.environmentAction)
		mux.HandleFunc("DELETE /api/environment/{id}", app.environmentAction)
	}

	mux.HandleFunc("OPTIONS /", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, POST, DELETE")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization, If-Match")
		w.WriteHeader(http.StatusNoContent)
	})
	mux.HandleFunc("GET /api/", app.getDashboard)

	mux.HandleFunc("GET /api/project", app.getAllProjects)
	mux.HandleFunc("GET /api/project/pinned", app.getPinnedProjects)
	mux.HandleFunc("GET /api/project/checklist/{projectId}", app.getProjectChecklists)

	mux.HandleFunc("PUT /api/project/bulk/pinned", app.bulkSetProjectsPinned)
	mux.HandleFunc("POST /api/project/bulk/delete", app.bulkDeleteProjects)

	mux.HandleFunc("GET /api/project/{projectId}/settings/workflow", app.getProjectWorkflowSettings)
	mux.HandleFunc("GET /api/project/{projectId}/settings/conductor", app.getConductor)
	mux.HandleFunc("PUT /api/project/{projectId}/settings/conductor", app.putConductor)
	mux.HandleFunc("POST /api/project/{projectId}/conductor/bulk", app.bulkConductor)
	mux.HandleFunc("PUT /api/project/{projectId}/settings/workflow", app.switchProjectWorkflow)
	mux.HandleFunc("GET /api/project/{projectId}/settings/task-types", app.getProjectTaskTypeSettings)
	mux.HandleFunc("PUT /api/project/{projectId}/settings/task-types", app.putProjectTaskTypes)
	mux.HandleFunc("GET /api/project/{projectId}/settings/task-types/enabled", app.getProjectTaskTypes)
	mux.HandleFunc("POST /api/project/{projectId}/settings/task-types/bulk/enable-category", app.postEnableTaskTypeCategory)
	mux.HandleFunc("GET /api/project/{projectId}", app.getProject)
	mux.HandleFunc("PUT /api/project/{projectId}", app.putProject)
	mux.HandleFunc("DELETE /api/project/{projectId}", app.deleteProject)
	mux.HandleFunc("POST /api/project", app.postProject)

	mux.HandleFunc("GET /api/tasks", app.getUpcomingTasks)
	mux.HandleFunc("GET /api/tasks/facets", app.getTaskFacets)
	mux.HandleFunc("GET /api/task/{taskId}", app.getTask)
	mux.HandleFunc("GET /api/task/body/{taskId}", app.getTaskBody)
	mux.HandleFunc("PUT /api/task/body/{taskId}", app.putTaskBody)
	mux.HandleFunc("POST /api/task", app.postTask)
	mux.HandleFunc("PUT /api/task", app.putTask)
	mux.HandleFunc("POST /api/task/{taskId}/transition", app.transitionTaskStage)
	mux.HandleFunc("POST /api/task/{taskId}/request-agent", app.requestAgent)
	mux.HandleFunc("PUT /api/task/bulk", app.bulkUpdateTasks)
	mux.HandleFunc("POST /api/task/bulk/delete", app.bulkDeleteTasks)
	mux.HandleFunc("DELETE /api/task/{taskId}", app.deleteTask)
	mux.HandleFunc("GET /api/task/relationships/{taskId}", app.getTaskRelationships)

	mux.HandleFunc("GET /api/task-relationship-type", app.getAllTaskRelationshipTypes)
	mux.HandleFunc("POST /api/task-relationship-type", app.postTaskRelationshipType)
	mux.HandleFunc("PUT /api/task-relationship-type/bulk/behavior", app.bulkUpdateRelationshipTypeBehavior)
	mux.HandleFunc("POST /api/task-relationship-type/bulk/delete", app.bulkDeleteRelationshipTypes)
	mux.HandleFunc("PUT /api/task-relationship-type/{id}", app.putTaskRelationshipType)
	mux.HandleFunc("PATCH /api/task-relationship-type/{id}/icon", app.patchTaskRelationshipTypeIcon)
	mux.HandleFunc("PATCH /api/task-relationship-type/{id}/names", app.patchTaskRelationshipTypeNames)
	mux.HandleFunc("DELETE /api/task-relationship-type/{id}", app.deleteTaskRelationshipType)
	mux.HandleFunc("POST /api/task-relationship", app.createTaskRelationship)
	mux.HandleFunc("POST /api/task-relationship/bulk", app.bulkCreateTaskRelationships)
	mux.HandleFunc("DELETE /api/task-relationship/{id}", app.deleteTaskRelationship)

	mux.HandleFunc("POST /api/checklist/{projectId}", app.postChecklist)
	mux.HandleFunc("PUT /api/checklist", app.putChecklist)
	mux.HandleFunc("DELETE /api/checklist/{checklistId}", app.deleteChecklist)

	mux.HandleFunc("GET /api/task-type", app.getAllTaskTypes)
	mux.HandleFunc("POST /api/task-type", app.postTaskType)
	mux.HandleFunc("PUT /api/task-type/bulk", app.bulkUpdateTaskTypes)
	mux.HandleFunc("POST /api/task-type/bulk/delete", app.bulkDeleteTaskTypes)
	mux.HandleFunc("PUT /api/task-type/{id}", app.putTaskType)
	mux.HandleFunc("DELETE /api/task-type/{id}", app.deleteTaskType)

	mux.HandleFunc("GET /api/task-type-category", app.getAllTaskTypeCategories)
	mux.HandleFunc("POST /api/task-type-category", app.postTaskTypeCategory)
	mux.HandleFunc("PUT /api/task-type-category/reorder", app.putTaskTypeCategoryReorder)
	mux.HandleFunc("PUT /api/task-type-category/{id}", app.putTaskTypeCategory)
	mux.HandleFunc("DELETE /api/task-type-category/{id}", app.deleteTaskTypeCategory)

	mux.HandleFunc("GET /api/workflow", app.getAllWorkflows)
	mux.HandleFunc("POST /api/workflow/bulk/delete", app.bulkDeleteWorkflows)
	mux.HandleFunc("POST /api/workflow/bulk/duplicate", app.bulkDuplicateWorkflows)
	mux.HandleFunc("GET /api/workflow/{workflowId}", app.getWorkflow)
	mux.HandleFunc("POST /api/workflow", app.postWorkflow)
	mux.HandleFunc("PUT /api/workflow/{workflowId}", app.putWorkflow)
	mux.HandleFunc("DELETE /api/workflow/{workflowId}", app.deleteWorkflow)
	mux.HandleFunc("PUT /api/workflow/{workflowId}/stages/order", app.putWorkflowStagesOrder)
	mux.HandleFunc("PUT /api/workflow/{workflowId}/stages/move", app.bulkMoveStages)
	mux.HandleFunc("POST /api/workflow/{workflowId}/stage", app.postStage)

	mux.HandleFunc("GET /api/stage", app.getAllStages)
	mux.HandleFunc("PUT /api/stage/bulk/type", app.bulkSetStageType)
	mux.HandleFunc("PUT /api/stage/bulk/color", app.bulkSetStageColor)
	mux.HandleFunc("PUT /api/stage/bulk/icon", app.bulkSetStageIcon)
	mux.HandleFunc("POST /api/stage/bulk/delete", app.bulkDeleteStages)
	mux.HandleFunc("PUT /api/stage/{stageId}", app.putStage)
	mux.HandleFunc("DELETE /api/stage/{stageId}", app.deleteStage)

	mux.HandleFunc("GET /api/persona", app.getAllPersonas)
	mux.HandleFunc("POST /api/persona", app.postPersona)
	mux.HandleFunc("POST /api/persona/bulk", app.bulkCreatePersonas)
	mux.HandleFunc("PUT /api/persona/bulk", app.bulkUpdatePersonas)
	mux.HandleFunc("POST /api/persona/bulk/delete", app.bulkDeletePersonas)
	mux.HandleFunc("GET /api/persona/{personaId}", app.getPersona)
	mux.HandleFunc("PUT /api/persona/{personaId}", app.putPersona)
	mux.HandleFunc("DELETE /api/persona/{personaId}", app.deletePersona)
	mux.HandleFunc("GET /api/mcp/tools", app.getMCPTools)

	// Legacy binding data remains editable for compatibility; it never triggers execution.
	mux.HandleFunc("PUT /api/stage/{stageId}/persona", app.putStagePersona)
	mux.HandleFunc("DELETE /api/stage/{stageId}/persona", app.deleteStagePersona)
	mux.HandleFunc("GET /api/ai/settings", app.getAISettings)
	mux.HandleFunc("PUT /api/ai/settings", app.putAISettings)
	mux.HandleFunc("POST /api/ai/tasks/{taskId}/runs", app.startAIRun)
	mux.HandleFunc("POST /api/ai/runs/{jobId}/cancel", app.cancelAIRun)
	mux.HandleFunc("GET /api/ai/tasks/{taskId}/branches", app.getTaskBranches)
	mux.HandleFunc("GET /api/ai/tasks/{taskId}/branches/{jobId}/merge", app.previewTaskMerge)
	mux.HandleFunc("POST /api/ai/tasks/{taskId}/branches/{jobId}/merge", app.mergeTaskBranch)
	mux.HandleFunc("GET /api/agent-jobs", app.getAgentJobs)
	mux.HandleFunc("GET /api/agent-jobs/{taskId}", app.getAgentJobsForTask)

	if spa := spaHandler(); spa != nil {
		mux.Handle("GET /", spa)
	}

	return withCommon(previewGuard(mux))
}
