/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppPersonasRouteImport } from './routes/app/personas'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTaskLinksRouteImport } from './routes/app/task-links'
import { Route as AppTaskTypesRouteImport } from './routes/app/task-types'
import { Route as AppUpcomingRouteImport } from './routes/app/upcoming'
import { Route as AppUsageRouteImport } from './routes/app/usage'
import { Route as AppWorkflowsRouteImport } from './routes/app/workflows'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AppPersonasIndexRouteImport } from './routes/app/personas.index'
import { Route as AppProjectProjectIdRouteImport } from './routes/app/project.$projectId'
import { Route as AppTaskTaskIdRouteImport } from './routes/app/task.$taskId'
import { Route as AppWorkflowWorkflowIdRouteImport } from './routes/app/workflow.$workflowId'
import { Route as AppProjectSettingsProjectIdRouteImport } from './routes/app/project.settings.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPersonasRoute = AppPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTaskLinksRoute = AppTaskLinksRouteImport.update({
  id: '/task-links',
  path: '/task-links',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTaskTypesRoute = AppTaskTypesRouteImport.update({
  id: '/task-types',
  path: '/task-types',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUpcomingRoute = AppUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRouteRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPersonasIndexRoute = AppPersonasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPersonasRoute,
} as any)
const AppProjectProjectIdRoute = AppProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTaskTaskIdRoute = AppTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkflowWorkflowIdRoute = AppWorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectSettingsProjectIdRoute =
  AppProjectSettingsProjectIdRouteImport.update({
    id: '/project/settings/$projectId',
    path: '/project/settings/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/personas': typeof AppPersonasRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/task-links': typeof AppTaskLinksRoute
  '/app/task-types': typeof AppTaskTypesRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/usage': typeof AppUsageRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
  '/app/personas/': typeof AppPersonasIndexRoute
  '/app/project/settings/$projectId': typeof AppProjectSettingsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/task-links': typeof AppTaskLinksRoute
  '/app/task-types': typeof AppTaskTypesRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/usage': typeof AppUsageRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/app': typeof AppIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
  '/app/personas': typeof AppPersonasIndexRoute
  '/app/project/settings/$projectId': typeof AppProjectSettingsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/personas': typeof AppPersonasRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/task-links': typeof AppTaskLinksRoute
  '/app/task-types': typeof AppTaskTypesRoute
  '/app/upcoming': typeof AppUpcomingRoute
  '/app/usage': typeof AppUsageRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/app/': typeof AppIndexRoute
  '/app/project/$projectId': typeof AppProjectProjectIdRoute
  '/app/task/$taskId': typeof AppTaskTaskIdRoute
  '/app/workflow/$workflowId': typeof AppWorkflowWorkflowIdRoute
  '/app/personas/': typeof AppPersonasIndexRoute
  '/app/project/settings/$projectId': typeof AppProjectSettingsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/personas'
    | '/app/settings'
    | '/app/task-links'
    | '/app/task-types'
    | '/app/upcoming'
    | '/app/usage'
    | '/app/workflows'
    | '/invite/$code'
    | '/app/'
    | '/app/project/$projectId'
    | '/app/task/$taskId'
    | '/app/workflow/$workflowId'
    | '/app/personas/'
    | '/app/project/settings/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/settings'
    | '/app/task-links'
    | '/app/task-types'
    | '/app/upcoming'
    | '/app/usage'
    | '/app/workflows'
    | '/invite/$code'
    | '/app'
    | '/app/project/$projectId'
    | '/app/task/$taskId'
    | '/app/workflow/$workflowId'
    | '/app/personas'
    | '/app/project/settings/$projectId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/personas'
    | '/app/settings'
    | '/app/task-links'
    | '/app/task-types'
    | '/app/upcoming'
    | '/app/usage'
    | '/app/workflows'
    | '/invite/$code'
    | '/app/'
    | '/app/project/$projectId'
    | '/app/task/$taskId'
    | '/app/workflow/$workflowId'
    | '/app/personas/'
    | '/app/project/settings/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/personas': {
      id: '/app/personas'
      path: '/personas'
      fullPath: '/app/personas'
      preLoaderRoute: typeof AppPersonasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/task-links': {
      id: '/app/task-links'
      path: '/task-links'
      fullPath: '/app/task-links'
      preLoaderRoute: typeof AppTaskLinksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/task-types': {
      id: '/app/task-types'
      path: '/task-types'
      fullPath: '/app/task-types'
      preLoaderRoute: typeof AppTaskTypesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/upcoming': {
      id: '/app/upcoming'
      path: '/upcoming'
      fullPath: '/app/upcoming'
      preLoaderRoute: typeof AppUpcomingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/personas/': {
      id: '/app/personas/'
      path: '/'
      fullPath: '/app/personas/'
      preLoaderRoute: typeof AppPersonasIndexRouteImport
      parentRoute: typeof AppPersonasRoute
    }
    '/app/project/$projectId': {
      id: '/app/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/app/project/$projectId'
      preLoaderRoute: typeof AppProjectProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/task/$taskId': {
      id: '/app/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/app/task/$taskId'
      preLoaderRoute: typeof AppTaskTaskIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workflow/$workflowId': {
      id: '/app/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/app/workflow/$workflowId'
      preLoaderRoute: typeof AppWorkflowWorkflowIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/project/settings/$projectId': {
      id: '/app/project/settings/$projectId'
      path: '/project/settings/$projectId'
      fullPath: '/app/project/settings/$projectId'
      preLoaderRoute: typeof AppProjectSettingsProjectIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppPersonasRouteChildren {
  AppPersonasIndexRoute: typeof AppPersonasIndexRoute
}

const AppPersonasRouteChildren: AppPersonasRouteChildren = {
  AppPersonasIndexRoute: AppPersonasIndexRoute,
}

const AppPersonasRouteWithChildren = AppPersonasRoute._addFileChildren(
  AppPersonasRouteChildren,
)

interface AppRouteRouteChildren {
  AppPersonasRoute: typeof AppPersonasRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTaskLinksRoute: typeof AppTaskLinksRoute
  AppTaskTypesRoute: typeof AppTaskTypesRoute
  AppUpcomingRoute: typeof AppUpcomingRoute
  AppUsageRoute: typeof AppUsageRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectProjectIdRoute: typeof AppProjectProjectIdRoute
  AppTaskTaskIdRoute: typeof AppTaskTaskIdRoute
  AppWorkflowWorkflowIdRoute: typeof AppWorkflowWorkflowIdRoute
  AppProjectSettingsProjectIdRoute: typeof AppProjectSettingsProjectIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPersonasRoute: AppPersonasRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTaskLinksRoute: AppTaskLinksRoute,
  AppTaskTypesRoute: AppTaskTypesRoute,
  AppUpcomingRoute: AppUpcomingRoute,
  AppUsageRoute: AppUsageRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectProjectIdRoute: AppProjectProjectIdRoute,
  AppTaskTaskIdRoute: AppTaskTaskIdRoute,
  AppWorkflowWorkflowIdRoute: AppWorkflowWorkflowIdRoute,
  AppProjectSettingsProjectIdRoute: AppProjectSettingsProjectIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
