/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TaskTypesRouteImport } from './routes/task-types'
import { Route as TaskLinksRouteImport } from './routes/task-links'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonasIndexRouteImport } from './routes/personas.index'
import { Route as WorkflowWorkflowIdRouteImport } from './routes/workflow.$workflowId'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as PersonasPersonaIdRouteImport } from './routes/personas.$personaId'
import { Route as ProjectSettingsProjectIdRouteImport } from './routes/project.settings.$projectId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTypesRoute = TaskTypesRouteImport.update({
  id: '/task-types',
  path: '/task-types',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskLinksRoute = TaskLinksRouteImport.update({
  id: '/task-links',
  path: '/task-links',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasIndexRoute = PersonasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonasRoute,
} as any)
const WorkflowWorkflowIdRoute = WorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasPersonaIdRoute = PersonasPersonaIdRouteImport.update({
  id: '/$personaId',
  path: '/$personaId',
  getParentRoute: () => PersonasRoute,
} as any)
const ProjectSettingsProjectIdRoute =
  ProjectSettingsProjectIdRouteImport.update({
    id: '/project/settings/$projectId',
    path: '/project/settings/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/personas': typeof PersonasRouteWithChildren
  '/settings': typeof SettingsRoute
  '/task-links': typeof TaskLinksRoute
  '/task-types': typeof TaskTypesRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/personas/$personaId': typeof PersonasPersonaIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/personas/': typeof PersonasIndexRoute
  '/project/settings/$projectId': typeof ProjectSettingsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/task-links': typeof TaskLinksRoute
  '/task-types': typeof TaskTypesRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/personas/$personaId': typeof PersonasPersonaIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/personas': typeof PersonasIndexRoute
  '/project/settings/$projectId': typeof ProjectSettingsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/personas': typeof PersonasRouteWithChildren
  '/settings': typeof SettingsRoute
  '/task-links': typeof TaskLinksRoute
  '/task-types': typeof TaskTypesRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/personas/$personaId': typeof PersonasPersonaIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/personas/': typeof PersonasIndexRoute
  '/project/settings/$projectId': typeof ProjectSettingsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/personas'
    | '/settings'
    | '/task-links'
    | '/task-types'
    | '/upcoming'
    | '/usage'
    | '/workflows'
    | '/personas/$personaId'
    | '/project/$projectId'
    | '/task/$taskId'
    | '/workflow/$workflowId'
    | '/personas/'
    | '/project/settings/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/task-links'
    | '/task-types'
    | '/upcoming'
    | '/usage'
    | '/workflows'
    | '/personas/$personaId'
    | '/project/$projectId'
    | '/task/$taskId'
    | '/workflow/$workflowId'
    | '/personas'
    | '/project/settings/$projectId'
  id:
    | '__root__'
    | '/'
    | '/personas'
    | '/settings'
    | '/task-links'
    | '/task-types'
    | '/upcoming'
    | '/usage'
    | '/workflows'
    | '/personas/$personaId'
    | '/project/$projectId'
    | '/task/$taskId'
    | '/workflow/$workflowId'
    | '/personas/'
    | '/project/settings/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonasRoute: typeof PersonasRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TaskLinksRoute: typeof TaskLinksRoute
  TaskTypesRoute: typeof TaskTypesRoute
  UpcomingRoute: typeof UpcomingRoute
  UsageRoute: typeof UsageRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
  WorkflowWorkflowIdRoute: typeof WorkflowWorkflowIdRoute
  ProjectSettingsProjectIdRoute: typeof ProjectSettingsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-types': {
      id: '/task-types'
      path: '/task-types'
      fullPath: '/task-types'
      preLoaderRoute: typeof TaskTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-links': {
      id: '/task-links'
      path: '/task-links'
      fullPath: '/task-links'
      preLoaderRoute: typeof TaskLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas/': {
      id: '/personas/'
      path: '/'
      fullPath: '/personas/'
      preLoaderRoute: typeof PersonasIndexRouteImport
      parentRoute: typeof PersonasRoute
    }
    '/workflow/$workflowId': {
      id: '/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof WorkflowWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas/$personaId': {
      id: '/personas/$personaId'
      path: '/$personaId'
      fullPath: '/personas/$personaId'
      preLoaderRoute: typeof PersonasPersonaIdRouteImport
      parentRoute: typeof PersonasRoute
    }
    '/project/settings/$projectId': {
      id: '/project/settings/$projectId'
      path: '/project/settings/$projectId'
      fullPath: '/project/settings/$projectId'
      preLoaderRoute: typeof ProjectSettingsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PersonasRouteChildren {
  PersonasPersonaIdRoute: typeof PersonasPersonaIdRoute
  PersonasIndexRoute: typeof PersonasIndexRoute
}

const PersonasRouteChildren: PersonasRouteChildren = {
  PersonasPersonaIdRoute: PersonasPersonaIdRoute,
  PersonasIndexRoute: PersonasIndexRoute,
}

const PersonasRouteWithChildren = PersonasRoute._addFileChildren(
  PersonasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonasRoute: PersonasRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TaskLinksRoute: TaskLinksRoute,
  TaskTypesRoute: TaskTypesRoute,
  UpcomingRoute: UpcomingRoute,
  UsageRoute: UsageRoute,
  WorkflowsRoute: WorkflowsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
  WorkflowWorkflowIdRoute: WorkflowWorkflowIdRoute,
  ProjectSettingsProjectIdRoute: ProjectSettingsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
